CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE team (
    id UUID PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE team_member (
    id UUID PRIMARY KEY,
    team_id UUID NOT NULL,
    user_id UUID NOT NULL,
    role VARCHAR(255)
);

CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP(6)
);

CREATE TABLE role_permission (
    role_id BIGINT NOT NULL REFERENCES role(id),
    permission_id BIGINT NOT NULL REFERENCES permission(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL,
    email VARCHAR(255),
    role VARCHAR(255),
    team_id UUID,
    ttl NUMERIC(21, 0) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(255)
);

CREATE TABLE flow (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    team_id UUID,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_by UUID,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT
);

CREATE TABLE node (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    flow_id UUID NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    created_by UUID,
    position NUMERIC(38, 0),
    duration NUMERIC(21, 0) NOT NULL,
    email VARCHAR(255)
);

CREATE TABLE tasks (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    team_id UUID,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE escalation (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    task_id UUID,
    flow_id UUID,
    status VARCHAR(255),
    team_id UUID,
    resolution_type VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    issue_solved_by VARCHAR(255)
);

CREATE TABLE flow_execution_state (
    id UUID PRIMARY KEY,
    execution_state VARCHAR(255),
    notification_state VARCHAR(255),
    task_id UUID,
    task_details VARCHAR(255),
    node_id UUID,
    user_email VARCHAR(255),
    duration NUMERIC(21, 0),
    position NUMERIC(38, 0),
    process_id UUID,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    retry_on_failure_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    max_retry_attempts INTEGER NOT NULL DEFAULT 0,
    send_attempt_count INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX users_email_uq ON users(email);
CREATE UNIQUE INDEX invite_token_uq ON invite(token);
CREATE INDEX team_member_team_id_idx ON team_member(team_id);
CREATE INDEX team_member_user_id_idx ON team_member(user_id);
CREATE INDEX node_flow_id_idx ON node(flow_id);
CREATE INDEX tasks_team_id_idx ON tasks(team_id);
