apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: alertops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: alertops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432