apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: alertops
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: alertops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi